stages:
     - deploy

deploy:
    stage: deploy
    only:
        - master
    image: alpine:3.12.1
    script:
        - apk add --no-cache rsync openssh
        - mkdir -p ~/.ssh
        - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - rsync -rav * deploy@${SSH_SERVER_PRD}:/home/normal/public_html/${URL_PRD}/
        - ssh deploy@${SSH_SERVER_PRD} "cd /home/normal/public_html/${URL_PRD} && composer install --no-dev --optimize-autoloader"
        - ssh deploy@${SSH_SERVER_PRD} php /home/normal/public_html/${URL_PRD}/artisan migrate --force